dist: trusty
sudo: required
serivces:
  - docker

language: python
env:
  - CC=musl-gcc     # Default to musl libc
matrix:
  include:
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"

    # Test using glibc
    - python: "3.5"
      env: CC=

    - python: "3.5-dev" # 3.5 development branch
    - python: "nightly" # currently points to 3.6-dev
  allow_failures:
    - python: "nightly"

addons:
  apt:
    packages:
      - musl
      - musl-dev
      - musl-tools

script:
  # Build and install a wheel
  - python setup.py bdist_wheel
  - pip install dist/staticx-*-py2.py3-none-any.whl
  - staticx --version

  # Run test against system executable
  - test/date.sh

  # Run PyInstaller test
  - test/pyinstall/run_test.sh
