dist: trusty
sudo: required
serivces:
  - docker

language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

matrix:
  allow_failures:
    - python: "nightly"

addons:
  apt:
    packages:
      - musl
      - musl-dev
      - musl-tools

env:
  global:
    - CC=musl-gcc

script:
  # Build and install a wheel
  - python setup.py bdist_wheel
  - pip install dist/staticx-*-py2.py3-none-any.whl
  - staticx --version

  # Run test against system executable
  - test/date.sh

  # Run PyInstaller test
  - test/pyinstall/run_test.sh
